In [2]:
# import necessary libraries    
import numpy as np  
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import researchpy as rp

In [3]:
! pip install pycaret

Requirement already satisfied: pycaret in c:\users\shaki\anaconda3\lib\site-packages (3.3.2)
Requirement already satisfied: ipython>=5.5.0 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (8.15.0)
Requirement already satisfied: ipywidgets>=7.6.5 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (8.0.4)
Requirement already satisfied: tqdm>=4.62.0 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (4.65.0)
Requirement already satisfied: numpy<1.27,>=1.21 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (1.24.3)
Requirement already satisfied: pandas<2.2.0 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (2.0.3)
Requirement already satisfied: jinja2>=3 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (3.1.2)
Requirement already satisfied: scipy<=1.11.4,>=1.6.1 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (1.11.1)
Requirement already satisfied: joblib<1.4,>=1.2.0 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (1.2.0)
Requirement already satisfied: scikit-learn>1.4.0 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (1.4.2)
Requirement already satisfied: pyod>=1.1.3 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (2.0.2)
Requirement already satisfied: imbalanced-learn>=0.12.0 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (0.12.3)
Requirement already satisfied: category-encoders>=2.4.0 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (2.6.3)
Requirement already satisfied: lightgbm>=3.0.0 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (4.5.0)
Requirement already satisfied: numba>=0.55.0 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (0.57.1)
Requirement already satisfied: requests>=2.27.1 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (2.31.0)
Requirement already satisfied: psutil>=5.9.0 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (5.9.0)
Requirement already satisfied: markupsafe>=2.0.1 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (2.1.1)
Requirement already satisfied: importlib-metadata>=4.12.0 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (6.0.0)
Requirement already satisfied: nbformat>=4.2.0 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (5.9.2)
Requirement already satisfied: cloudpickle in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (2.2.1)
Requirement already satisfied: deprecation>=2.1.0 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (2.1.0)
Requirement already satisfied: xxhash in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (2.0.2)
Requirement already satisfied: matplotlib<3.8.0 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (3.7.2)
Requirement already satisfied: scikit-plot>=0.3.7 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (0.3.7)
Requirement already satisfied: yellowbrick>=1.4 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (1.5)
Requirement already satisfied: plotly>=5.14.0 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (5.24.0)
Requirement already satisfied: kaleido>=0.2.1 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (0.2.1)
Requirement already satisfied: schemdraw==0.15 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (0.15)
Requirement already satisfied: plotly-resampler>=0.8.3.1 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (0.10.0)
Requirement already satisfied: statsmodels>=0.12.1 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (0.14.0)
Requirement already satisfied: sktime==0.26.0 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (0.26.0)
Requirement already satisfied: tbats>=1.1.3 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (1.1.3)
Requirement already satisfied: pmdarima>=2.0.4 in c:\users\shaki\anaconda3\lib\site-packages (from pycaret) (2.0.4)
Requirement already satisfied: packaging in c:\users\shaki\anaconda3\lib\site-packages (from sktime==0.26.0->pycaret) (23.1)
Requirement already satisfied: scikit-base<0.8.0 in c:\users\shaki\anaconda3\lib\site-packages (from sktime==0.26.0->pycaret) (0.7.8)
Requirement already satisfied: patsy>=0.5.1 in c:\users\shaki\anaconda3\lib\site-packages (from category-encoders>=2.4.0->pycaret) (0.5.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\shaki\anaconda3\lib\site-packages (from imbalanced-learn>=0.12.0->pycaret) (2.2.0)
Requirement already satisfied: zipp>=0.5 in c:\users\shaki\anaconda3\lib\site-packages (from importlib-metadata>=4.12.0->pycaret) (3.11.0)
Requirement already satisfied: backcall in c:\users\shaki\anaconda3\lib\site-packages (from ipython>=5.5.0->pycaret) (0.2.0)
Requirement already satisfied: decorator in c:\users\shaki\anaconda3\lib\site-packages (from ipython>=5.5.0->pycaret) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\shaki\anaconda3\lib\site-packages (from ipython>=5.5.0->pycaret) (0.18.1)
Requirement already satisfied: matplotlib-inline in c:\users\shaki\anaconda3\lib\site-packages (from ipython>=5.5.0->pycaret) (0.1.6)
Requirement already satisfied: pickleshare in c:\users\shaki\anaconda3\lib\site-packages (from ipython>=5.5.0->pycaret) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in c:\users\shaki\anaconda3\lib\site-packages (from ipython>=5.5.0->pycaret) (3.0.36)
Requirement already satisfied: pygments>=2.4.0 in c:\users\shaki\anaconda3\lib\site-packages (from ipython>=5.5.0->pycaret) (2.15.1)
Requirement already satisfied: stack-data in c:\users\shaki\anaconda3\lib\site-packages (from ipython>=5.5.0->pycaret) (0.2.0)
Requirement already satisfied: traitlets>=5 in c:\users\shaki\anaconda3\lib\site-packages (from ipython>=5.5.0->pycaret) (5.7.1)
Requirement already satisfied: colorama in c:\users\shaki\anaconda3\lib\site-packages (from ipython>=5.5.0->pycaret) (0.4.6)
Requirement already satisfied: ipykernel>=4.5.1 in c:\users\shaki\anaconda3\lib\site-packages (from ipywidgets>=7.6.5->pycaret) (6.25.0)
Requirement already satisfied: widgetsnbextension~=4.0 in c:\users\shaki\anaconda3\lib\site-packages (from ipywidgets>=7.6.5->pycaret) (4.0.5)
Requirement already satisfied: jupyterlab-widgets~=3.0 in c:\users\shaki\anaconda3\lib\site-packages (from ipywidgets>=7.6.5->pycaret) (3.0.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\shaki\anaconda3\lib\site-packages (from matplotlib<3.8.0->pycaret) (1.0.5)
Requirement already satisfied: cycler>=0.10 in c:\users\shaki\anaconda3\lib\site-packages (from matplotlib<3.8.0->pycaret) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\shaki\anaconda3\lib\site-packages (from matplotlib<3.8.0->pycaret) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\shaki\anaconda3\lib\site-packages (from matplotlib<3.8.0->pycaret) (1.4.4)
Requirement already satisfied: pillow>=6.2.0 in c:\users\shaki\anaconda3\lib\site-packages (from matplotlib<3.8.0->pycaret) (10.2.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in c:\users\shaki\anaconda3\lib\site-packages (from matplotlib<3.8.0->pycaret) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\shaki\anaconda3\lib\site-packages (from matplotlib<3.8.0->pycaret) (2.8.2)
Requirement already satisfied: fastjsonschema in c:\users\shaki\anaconda3\lib\site-packages (from nbformat>=4.2.0->pycaret) (2.16.2)
Requirement already satisfied: jsonschema>=2.6 in c:\users\shaki\anaconda3\lib\site-packages (from nbformat>=4.2.0->pycaret) (4.17.3)
Requirement already satisfied: jupyter-core in c:\users\shaki\anaconda3\lib\site-packages (from nbformat>=4.2.0->pycaret) (5.3.0)
Requirement already satisfied: llvmlite<0.41,>=0.40.0dev0 in c:\users\shaki\anaconda3\lib\site-packages (from numba>=0.55.0->pycaret) (0.40.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\shaki\anaconda3\lib\site-packages (from pandas<2.2.0->pycaret) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\shaki\anaconda3\lib\site-packages (from pandas<2.2.0->pycaret) (2023.3)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\shaki\anaconda3\lib\site-packages (from plotly>=5.14.0->pycaret) (8.2.2)
Requirement already satisfied: dash>=2.9.0 in c:\users\shaki\anaconda3\lib\site-packages (from plotly-resampler>=0.8.3.1->pycaret) (2.18.0)
Requirement already satisfied: orjson<4.0.0,>=3.8.0 in c:\users\shaki\anaconda3\lib\site-packages (from plotly-resampler>=0.8.3.1->pycaret) (3.10.7)
Requirement already satisfied: tsdownsample>=0.1.3 in c:\users\shaki\anaconda3\lib\site-packages (from plotly-resampler>=0.8.3.1->pycaret) (0.1.3)
Requirement already satisfied: Cython!=0.29.18,!=0.29.31,>=0.29 in c:\users\shaki\anaconda3\lib\site-packages (from pmdarima>=2.0.4->pycaret) (3.0.11)
Requirement already satisfied: urllib3 in c:\users\shaki\anaconda3\lib\site-packages (from pmdarima>=2.0.4->pycaret) (1.26.16)
Requirement already satisfied: setuptools!=50.0.0,>=38.6.0 in c:\users\shaki\anaconda3\lib\site-packages (from pmdarima>=2.0.4->pycaret) (68.0.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\shaki\anaconda3\lib\site-packages (from requests>=2.27.1->pycaret) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\shaki\anaconda3\lib\site-packages (from requests>=2.27.1->pycaret) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\shaki\anaconda3\lib\site-packages (from requests>=2.27.1->pycaret) (2024.2.2)
Requirement already satisfied: Flask<3.1,>=1.0.4 in c:\users\shaki\anaconda3\lib\site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (2.2.2)
Requirement already satisfied: Werkzeug<3.1 in c:\users\shaki\anaconda3\lib\site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (2.2.3)
Requirement already satisfied: dash-html-components==2.0.0 in c:\users\shaki\anaconda3\lib\site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (2.0.0)
Requirement already satisfied: dash-core-components==2.0.0 in c:\users\shaki\anaconda3\lib\site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (2.0.0)
Requirement already satisfied: dash-table==5.0.0 in c:\users\shaki\anaconda3\lib\site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (5.0.0)
Requirement already satisfied: typing-extensions>=4.1.1 in c:\users\shaki\anaconda3\lib\site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (4.7.1)
Requirement already satisfied: retrying in c:\users\shaki\anaconda3\lib\site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (1.3.4)
Requirement already satisfied: nest-asyncio in c:\users\shaki\anaconda3\lib\site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (1.5.6)
Requirement already satisfied: comm>=0.1.1 in c:\users\shaki\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (0.1.2)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\shaki\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (1.6.7)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\users\shaki\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (7.4.9)
Requirement already satisfied: pyzmq>=20 in c:\users\shaki\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (23.2.0)
Requirement already satisfied: tornado>=6.1 in c:\users\shaki\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (6.3.2)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\shaki\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=5.5.0->pycaret) (0.8.3)
Requirement already satisfied: attrs>=17.4.0 in c:\users\shaki\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (22.1.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\shaki\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (0.18.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\shaki\anaconda3\lib\site-packages (from jupyter-core->nbformat>=4.2.0->pycaret) (3.10.0)
Requirement already satisfied: pywin32>=300 in c:\users\shaki\anaconda3\lib\site-packages (from jupyter-core->nbformat>=4.2.0->pycaret) (305.1)
Requirement already satisfied: six in c:\users\shaki\anaconda3\lib\site-packages (from patsy>=0.5.1->category-encoders>=2.4.0->pycaret) (1.16.0)
Requirement already satisfied: wcwidth in c:\users\shaki\anaconda3\lib\site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython>=5.5.0->pycaret) (0.2.5)
Requirement already satisfied: executing in c:\users\shaki\anaconda3\lib\site-packages (from stack-data->ipython>=5.5.0->pycaret) (0.8.3)
Requirement already satisfied: asttokens in c:\users\shaki\anaconda3\lib\site-packages (from stack-data->ipython>=5.5.0->pycaret) (2.0.5)
Requirement already satisfied: pure-eval in c:\users\shaki\anaconda3\lib\site-packages (from stack-data->ipython>=5.5.0->pycaret) (0.2.2)
Requirement already satisfied: itsdangerous>=2.0 in c:\users\shaki\anaconda3\lib\site-packages (from Flask<3.1,>=1.0.4->dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (2.0.1)
Requirement already satisfied: click>=8.0 in c:\users\shaki\anaconda3\lib\site-packages (from Flask<3.1,>=1.0.4->dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (8.0.4)
Requirement already satisfied: entrypoints in c:\users\shaki\anaconda3\lib\site-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (0.4)

In [4]:
# Importing the dataset 
data=pd.read_csv('liver_patient.csv')

In [5]:
# Display the first 5 rows of the dataset
data.head()

,Age,Gender,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,Alamine_Aminotransferase,Aspartate_Aminotransferase,Total_Protiens,Albumin,Albumin_and_Globulin_Ratio,liver_disease
0,65,Female,0.7,0.1,187,16,18,6.8,3.3,0.90,1
1,62,Male,10.9,5.5,699,64,100,7.5,3.2,0.74,1
2,62,Male,7.3,4.1,490,60,68,7.0,3.3,0.89,1
3,58,Male,1.0,0.4,182,14,20,6.8,3.4,1.00,1
4,72,Male,3.9,2.0,195,27,59,7.3,2.4,0.40,1

In [6]:
data.shape

(583, 11)

In [7]:
# information about the dataset 
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 583 entries, 0 to 582
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         583 non-null    int64
 1   Gender                      583 non-null    object
 2   Total_Bilirubin             583 non-null    float64
 3   Direct_Bilirubin            583 non-null    float64
 4   Alkaline_Phosphotase        583 non-null    int64
 5   Alamine_Aminotransferase    583 non-null    int64
 6   Aspartate_Aminotransferase  583 non-null    int64
 7   Total_Protiens              583 non-null    float64
 8   Albumin                     583 non-null    float64
 9   Albumin_and_Globulin_Ratio  579 non-null    float64
 10  liver_disease               583 non-null    int64
dtypes: float64(5), int64(5), object(1)
memory usage: 50.2+ KB

In [8]:
# Checking for missing values   
data.isnull().sum()

Age                           0
Gender                        0
Total_Bilirubin               0
Direct_Bilirubin              0
Alkaline_Phosphotase          0
Alamine_Aminotransferase      0
Aspartate_Aminotransferase    0
Total_Protiens                0
Albumin                       0
Albumin_and_Globulin_Ratio    4
liver_disease                 0
dtype: int64

In [9]:
# Checking for duplicate values 
data.duplicated().sum()

13

In [10]:
# Descriptive statistics of the dataset 
data.describe()

,Age,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,Alamine_Aminotransferase,Aspartate_Aminotransferase,Total_Protiens,Albumin,Albumin_and_Globulin_Ratio,liver_disease
count,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,579.000000,583.000000
mean,44.746141,3.298799,1.486106,290.576329,80.713551,109.910806,6.483190,3.141852,0.947064,0.713551
std,16.189833,6.209522,2.808498,242.937989,182.620356,288.918529,1.085451,0.795519,0.319592,0.452490
min,4.000000,0.400000,0.100000,63.000000,10.000000,10.000000,2.700000,0.900000,0.300000,0.000000
25%,33.000000,0.800000,0.200000,175.500000,23.000000,25.000000,5.800000,2.600000,0.700000,0.000000
50%,45.000000,1.000000,0.300000,208.000000,35.000000,42.000000,6.600000,3.100000,0.930000,1.000000
75%,58.000000,2.600000,1.300000,298.000000,60.500000,87.000000,7.200000,3.800000,1.100000,1.000000
max,90.000000,75.000000,19.700000,2110.000000,2000.000000,4929.000000,9.600000,5.500000,2.800000,1.000000

In [11]:
# select numeric data 
num_cols = data.select_dtypes(exclude = 'object')
num_cols.head()

,Age,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,Alamine_Aminotransferase,Aspartate_Aminotransferase,Total_Protiens,Albumin,Albumin_and_Globulin_Ratio,liver_disease
0,65,0.7,0.1,187,16,18,6.8,3.3,0.90,1
1,62,10.9,5.5,699,64,100,7.5,3.2,0.74,1
2,62,7.3,4.1,490,60,68,7.0,3.3,0.89,1
3,58,1.0,0.4,182,14,20,6.8,3.4,1.00,1
4,72,3.9,2.0,195,27,59,7.3,2.4,0.40,1

In [12]:
# summary statistics of numerical variables 
rp.summary_cont(num_cols[['Age', 'Total_Bilirubin', 'Direct_Bilirubin', 'Alkaline_Phosphotase',
       'Alamine_Aminotransferase', 'Aspartate_Aminotransferase',
       'Total_Protiens', 'Albumin', 'Albumin_and_Globulin_Ratio']])

,Variable,N,Mean,SD,SE,95% Conf.,Interval
0,Age,583.0,44.7461,16.1898,0.6705,43.4292,46.0631
1,Total_Bilirubin,583.0,3.2988,6.2095,0.2572,2.7937,3.8039
2,Direct_Bilirubin,583.0,1.4861,2.8085,0.1163,1.2577,1.7146
3,Alkaline_Phosphotase,583.0,290.5763,242.9380,10.0615,270.8151,310.3375
4,Alamine_Aminotransferase,583.0,80.7136,182.6204,7.5634,65.8587,95.5684
5,Aspartate_Aminotransferase,583.0,109.9108,288.9185,11.9658,86.4094,133.4122
6,Total_Protiens,583.0,6.4832,1.0855,0.0450,6.3949,6.5715
7,Albumin,583.0,3.1419,0.7955,0.0329,3.0771,3.2066
8,Albumin_and_Globulin_Ratio,579.0,0.9471,0.3196,0.0133,0.9210,0.9732

In [13]:
# select categorical data 
cat_cols = data.select_dtypes(include = 'object')
cat_cols.head()

   Gender
0  Female
1    Male
2    Male
3    Male
4    Male

In [19]:
from sklearn.preprocessing import LabelEncoder

In [20]:
# correalation matrix   
correlation = data.corr(method='pearson')

ValueError: could not convert string to float: 'Female'